// Shared by the Docker scripts: .env with every secret Docker needs, and `docker compose` calls.
import { spawnSync } from "node:child_process";
import { appendFileSync, readFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { ENV_FILE, addGeneratedSecretsIfMissing, createEnvFileIfMissing, loadEnv, parseEnv } from "./env.mjs";
import { ROOT } from "./processes.mjs";

/** Creates .env if needed and adds generated secrets Docker needs (never changes a set value). */
export function ensureDockerEnv(log = console.log) {
  if (createEnvFileIfMissing()) log(`Created ${ENV_FILE} with generated secrets.`);
  if (addGeneratedSecretsIfMissing()) log(`Added a generated AI_SERVICE_KEY to ${ENV_FILE}.`);
  const current = parseEnv(readFileSync(ENV_FILE, "utf8"));
  if (!current.DOCKER_DB_PASSWORD) {
    appendFileSync(ENV_FILE, `\n# MySQL password inside Docker (generated by the Docker scripts).\nDOCKER_DB_PASSWORD=${randomBytes(24).toString("hex")}\n`);
    log(`Added a generated DOCKER_DB_PASSWORD to ${ENV_FILE}.`);
  }
  return loadEnv();
}

/** Runs `docker compose <args>` from the repository root; returns its exit code. */
export function compose(args, env = process.env) {
  const result = spawnSync("docker", ["compose", ...args], { cwd: ROOT, stdio: "inherit", env, shell: false });
  if (result.error) {
    throw new Error("Docker isn't available: install Docker Desktop (see README, \"Run with Docker\") and start it.");
  }
  return result.status ?? 1;
}
